name: spotikit
description: "Flutter plugin for Spotify App Remote integration on Android."
version: 2.0.0
homepage: https://github.com/ArdaKoksall/spotikit
issue_tracker: https://github.com/ArdaKoksall/spotikit
repository: https://github.com/ArdaKoksall/spotikit


environment:
  sdk: ^3.10.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.6.1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.ardakoksal.spotikit
        pluginClass: SpotikitPlugin

executables:
  android_init: android_init
  android_clean: android_clean
